development:
  adapter: mysql2
  database: cloud_development
  host: localhost
  username: root
  password:

production:
  adapter: mysql2
  database: cloud_production
  host: localhost
  username: root
  password: